version: '3.6'

networks: 
    frontend:
    backend:

volumes:
  produtosdata:
    
services:
  sql:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile.Sql
    volumes:
      - produtosdata:/var/lib/sql
    networks: 
      - backend

  webapi:
    container_name: webapi
    build: 
      context: .
      dockerfile: Dockerfile.Dev
    networks: 
      - backend
      - frontend
    ports:
      - 8080:5000
    environment: 
      - DBHOST=sql
    depends_on: 
      - sql